version: '2'

services:
  crawler:
    build: ../crawler
    restart: always
    links:
     - db
    environment:
     - DB_HOST=db
     - DB_PORT=28015
     - DB_NAME=powietrze
    mem_limit: 128M

  api:
    build: ../api
    restart: always
    links:
     - db
    environment:
     - DB_HOST=db
     - DB_PORT=28015
     - DB_NAME=powietrze
     - API_PORT=80
    ports:
     - 9000:80
    mem_limit: 128M

  db:
    image: rethinkdb:2.3.5
    restart: always
    ports:
     - 9010:8080
    volumes:
     - ./data:/data
    mem_limit: 512M
